//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetService.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetClaimService
    {
        public int Id { get; set; }
        public int PetId { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
        public Nullable<System.DateTime> SavedDate { get; set; }
        public Nullable<System.DateTime> PetClaimedDate { get; set; }
    
        public virtual PetList PetList { get; set; }
    }
}
