//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetService.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetList
    {
        public PetList()
        {
            this.PetClaimServices = new HashSet<PetClaimService>();
            this.PetClaimServiceTemps = new HashSet<PetClaimServiceTemp>();
        }
    
        public int PetId { get; set; }
        public string PetName { get; set; }
    
        public virtual ICollection<PetClaimService> PetClaimServices { get; set; }
        public virtual ICollection<PetClaimServiceTemp> PetClaimServiceTemps { get; set; }
    }
}
